### ISSUE TITLE
[bug] bug title 

### ISSUE THREAD

**Issue by GeekWorkCode** [labring/sealaf#3]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/sealaf/issues?q=is%3Aissue) and found no similar issues.

### Environment

Linux (self-host)

### What happened

[Nest] 1  - 05/23/2024, 5:47:25 AM   ERROR [InstanceTaskService] handleStartingPhase error
[Nest] 1  - 05/23/2024, 5:47:25 AM   ERROR [InstanceTaskService] HttpError: HTTP request failed
[Nest] 1  - 05/23/2024, 5:47:25 AM   DEBUG [InstanceTaskService] Object:
{
  "statusCode": 404,
  "body": "404 page not found\n",
  "headers": {
    "audit-id": "04a6667e-6199-4d20-be56-bda580bef66d",
    "cache-control": "no-cache, private",
    "content-type": "text/plain; charset=utf-8",
    "x-content-type-options": "nosniff",
    "x-kubernetes-pf-flowschema-uid": "7feb3836-35e6-46e9-9044-65e09bb2a7e3",
    "x-kubernetes-pf-prioritylevel-uid": "0bbcb2fc-e1d2-4c82-9ec1-da70a0bd7480",
    "date": "Thu, 23 May 2024 05:47:25 GMT",
    "content-length": "19",
    "connection": "close"
  },
  "request": {
    "uri": {
      "protocol": "https:",
      "slashes": true,
      "auth": null,
      "host": "10.96.0.1:443",
      "port": "443",
      "hostname": "10.96.0.1",
      "hash": null,
      "search": null,
      "query": null,
      "pathname": "/apis/objectstorage.sealos.io/v1/namespaces/ns-admin/objectstoragebuckets",
      "path": "/apis/objectstorage.sealos.io/v1/namespaces/ns-admin/objectstoragebuckets",
      "href": "https://10.96.0.1:443/apis/objectstorage.sealos.io/v1/namespaces/ns-admin/objectstoragebuckets"
    },
    "method": "POST",
    "headers": {
      "Accept": "application/json",
      "Authorization": "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImpmOGN3UUczTjlqMXhWQzhBMzJ1OFBhQ2IteVhaal9SUklRc05iQWp5NkEifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwi
ZXhwIjoxNzQ3OTc4ODk2LCJpYXQiOjE3MTY0NDI4OTYsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJzZWFsYWYtc3lzdGVtIiwicG9kIjp7Im5hbWUiOiJzZW
FsYWYtc2VydmVyLWY5N2Y1NmZmNC1uNmR3ZCIsInVpZCI6Ijc2OGQ3YjNlLWViNWYtNGU1Ni1hMzAzLWI4OWJjMjdhYTcwZCJ9LCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoic2VhbGFmLXNhIiwidWlkIjoiN2NhYjE4ZTMtZTM2YS00OTg1LTg5ZTUtY2ExZDc5
MTUwOWE3In0sIndhcm5hZnRlciI6MTcxNjQ0NjUwM30sIm5iZiI6MTcxNjQ0Mjg5Niwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnNlYWxhZi1zeXN0ZW06c2VhbGFmLXNhIn0.V0G7qBaeshj36pqxAeKCZu84MCZfLfPFtVsnjvqfnO8P9BQ5aC3x65NGkl
dW3pm-xx4_I7ZNLLPtonR_Wy2HuQjilwCKaWS2UEkM2QLsFRWYcZ0P4vXIR7eO0vHu3iqC9QL6sRpUDiztRsKPYCkAMvi-HCpad8ubhn7EgAgd1YIJby3nYWOdUs1tZd7RxppYj42-Oe1zOXkWrZ93GG0JCtb4WZFGAviYAPnwqyvl4UFo8XCtOf4oe7qGrOafAeOy
SSOVPb8XkiY02GEU5mzeNWnf5UY5jXrfF5Q5gvBrCZ8skAAnKarm2ZMSOMPyRzPGU0Mod-q-w-w4_BzmvlqcHw",
      "content-type": "application/json",
      "content-length": 173
    }
  }
}

### How to reproduce

Compile and install by yourself in the Linux arm64 environment：
sealos build -t docker.io/zacharywin/sealaf:latest --platform linux/arm64 -f Kubefile  .
sealos run docker.io/zacharywin/sealaf:latest --env cloudDomain="x.x.x.x"

1、Create my application, the status is always starting

2、View logs 
kubectl logs sealaf-server-f97f56ff4-n6dwd -n sealaf-system 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by 0fatal** [comment]
make sure to install object storage before

```bash
curl -O https://raw.githubusercontent.com/minio/operator/master/helm-releases/operator-5.0.6.tgz
helm install --namespace minio-system --create-namespace minio-operator operator-5.0.6.tgz


sealos run ghcr.io/labring/sealos-cloud-objectstorage:latest -e cloudDomain={DOMAIN}
```

**Comment by GeekWorkCode** [comment]
sealaf-system               sealaf-server-f97f56ff4-mxmnt                                     0/1     Pending

kubectl describe pod  sealaf-server-f97f56ff4-mxmnt -n sealaf-system

Name:             sealaf-server-f97f56ff4-mxmnt
Namespace:        sealaf-system
Priority:         0
Service Account:  sealaf-sa
Node:             <none>
Labels:           app=sealaf-server
                  app.kubernetes.io/name=sealaf-server
                  pod-template-hash=f97f56ff4
Annotations:      <none>
Status:           Pending
IP:               
IPs:              <none>
Controlled By:    ReplicaSet/sealaf-server-f97f56ff4
Containers:
  sealaf-server:
    Image:      docker.io/zacharywin/sealaf-server:sha-35487e0
    Port:       3000/TCP
    Host Port:  0/TCP
    Limits:
      cpu:     1
      memory:  2Gi
    Requests:
      cpu:      100m
      memory:   204Mi
    Liveness:   http-get http://:http/v1/regions delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:http/v1/regions delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      DATABASE_URL:                                         <set to the key 'DATABASE_URL' in secret 'sealaf-config'>          Optional: false
      JWT_SECRET:                                           <set to the key 'SERVER_JWT_SECRET' in secret 'sealaf-config'>     Optional: false
      APP_MONITOR_URL:                                      <set to the key 'APP_MONITOR_URL' in secret 'sealaf-config'>       Optional: false
      DATABASE_MONITOR_URL:                                 <set to the key 'DATABASE_MONITOR_URL' in secret 'sealaf-config'>  Optional: false
      API_SERVER_URL:                                       https://sealaf-api.sealos.buildapp.eu.org
      JWT_EXPIRES_IN:                                       7d
      DEFAULT_REGION_RUNTIME_DOMAIN:                        sealos.buildapp.eu.org
      DEFAULT_REGION_TLS_ENABLED:                           true
      DEFAULT_REGION_TLS_WILDCARD_CERTIFICATE_SECRET_NAME:  wildcard-cert
      DEFAULT_RUNTIME_INIT_IMAGE:                           docker.io/lafyun/runtime-node-init:latest
      DEFAULT_RUNTIME_IMAGE:                                docker.io/lafyun/runtime-node:latest
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-4j8zv (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  kube-api-access-4j8zv:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  53s   default-scheduler  0/1 nodes are available: 1 Insufficient cpu. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod..
  Warning  FailedScheduling  49s   default-scheduler  0/1 nodes are available: 1 Insufficient cpu. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod..

**Comment by GeekWorkCode** [comment]
> make sure to install object storage before
> 
> ```shell
> curl -O https://raw.githubusercontent.com/minio/operator/master/helm-releases/operator-5.0.6.tgz
> helm install --namespace minio-system --create-namespace minio-operator operator-5.0.6.tgz
> 
> 
> sealos run ghcr.io/labring/sealos-cloud-objectstorage:latest -e cloudDomain={DOMAIN}
> ```



> make sure to install object storage before
> 
> ```shell
> curl -O https://raw.githubusercontent.com/minio/operator/master/helm-releases/operator-5.0.6.tgz
> helm install --namespace minio-system --create-namespace minio-operator operator-5.0.6.tgz
> 
> 
> sealos run ghcr.io/labring/sealos-cloud-objectstorage:latest -e cloudDomain={DOMAIN}
> ```

sealaf-system               sealaf-server-f97f56ff4-mxmnt                                     0/1     Pending

kubectl describe pod  sealaf-server-f97f56ff4-mxmnt -n sealaf-system

Name:             sealaf-server-f97f56ff4-mxmnt
Namespace:        sealaf-system
Priority:         0
Service Account:  sealaf-sa
Node:             <none>
Labels:           app=sealaf-server
                  app.kubernetes.io/name=sealaf-server
                  pod-template-hash=f97f56ff4
Annotations:      <none>
Status:           Pending
IP:               
IPs:              <none>
Controlled By:    ReplicaSet/sealaf-server-f97f56ff4
Containers:
  sealaf-server:
    Image:      docker.io/zacharywin/sealaf-server:sha-35487e0
    Port:       3000/TCP
    Host Port:  0/TCP
    Limits:
      cpu:     1
      memory:  2Gi
    Requests:
      cpu:      100m
      memory:   204Mi
    Liveness:   http-get http://:http/v1/regions delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:http/v1/regions delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      DATABASE_URL:                                         <set to the key 'DATABASE_URL' in secret 'sealaf-config'>          Optional: false
      JWT_SECRET:                                           <set to the key 'SERVER_JWT_SECRET' in secret 'sealaf-config'>     Optional: false
      APP_MONITOR_URL:                                      <set to the key 'APP_MONITOR_URL' in secret 'sealaf-config'>       Optional: false
      DATABASE_MONITOR_URL:                                 <set to the key 'DATABASE_MONITOR_URL' in secret 'sealaf-config'>  Optional: false
      API_SERVER_URL:                                       https://sealaf-api.sealos.xxxx.xxxx
      JWT_EXPIRES_IN:                                       7d
      DEFAULT_REGION_RUNTIME_DOMAIN:                        sealos.xxxx.xxxx
      DEFAULT_REGION_TLS_ENABLED:                           true
      DEFAULT_REGION_TLS_WILDCARD_CERTIFICATE_SECRET_NAME:  wildcard-cert
      DEFAULT_RUNTIME_INIT_IMAGE:                           docker.io/lafyun/runtime-node-init:latest
      DEFAULT_RUNTIME_IMAGE:                                docker.io/lafyun/runtime-node:latest
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-4j8zv (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  kube-api-access-4j8zv:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  53s   default-scheduler  0/1 nodes are available: 1 Insufficient cpu. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod..
  Warning  FailedScheduling  49s   default-scheduler  0/1 nodes are available: 1 Insufficient cpu. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod..

**Comment by 0fatal** [comment]
Insufficient cpu

> > make sure to install object storage before
> > ```shell
> > curl -O https://raw.githubusercontent.com/minio/operator/master/helm-releases/operator-5.0.6.tgz
> > helm install --namespace minio-system --create-namespace minio-operator operator-5.0.6.tgz
> > 
> > 
> > sealos run ghcr.io/labring/sealos-cloud-objectstorage:latest -e cloudDomain={DOMAIN}
> > ```
> 
> > make sure to install object storage before
> > ```shell
> > curl -O https://raw.githubusercontent.com/minio/operator/master/helm-releases/operator-5.0.6.tgz
> > helm install --namespace minio-system --create-namespace minio-operator operator-5.0.6.tgz
> > 
> > 
> > sealos run ghcr.io/labring/sealos-cloud-objectstorage:latest -e cloudDomain={DOMAIN}
> > ```
> 
> sealaf-system sealaf-server-f97f56ff4-mxmnt 0/1 Pending
> 
> kubectl describe pod sealaf-server-f97f56ff4-mxmnt -n sealaf-system
> 
> Name: sealaf-server-f97f56ff4-mxmnt Namespace: sealaf-system Priority: 0 Service Account: sealaf-sa Node: Labels: app=sealaf-server app.kubernetes.io/name=sealaf-server pod-template-hash=f97f56ff4 Annotations: Status: Pending IP: IPs: Controlled By: ReplicaSet/sealaf-server-f97f56ff4 Containers: sealaf-server: Image: docker.io/zacharywin/sealaf-server:sha-35487e0 Port: 3000/TCP Host Port: 0/TCP Limits: cpu: 1 memory: 2Gi Requests: cpu: 100m memory: 204Mi Liveness: http-get http://:http/v1/regions delay=0s timeout=1s period=10s #success=1 #failure=3 Readiness: http-get http://:http/v1/regions delay=0s timeout=1s period=10s #success=1 #failure=3 Environment: DATABASE_URL: <set to the key 'DATABASE_URL' in secret 'sealaf-config'> Optional: false JWT_SECRET: <set to the key 'SERVER_JWT_SECRET' in secret 'sealaf-config'> Optional: false APP_MONITOR_URL: <set to the key 'APP_MONITOR_URL' in secret 'sealaf-config'> Optional: false DATABASE_MONITOR_URL: <set to the key 'DATABASE_MONITOR_URL' in secret 'sealaf-config'> Optional: false API_SERVER_URL: https://sealaf-api.sealos.xxxx.xxxx JWT_EXPIRES_IN: 7d DEFAULT_REGION_RUNTIME_DOMAIN: sealos.xxxx.xxxx DEFAULT_REGION_TLS_ENABLED: true DEFAULT_REGION_TLS_WILDCARD_CERTIFICATE_SECRET_NAME: wildcard-cert DEFAULT_RUNTIME_INIT_IMAGE: docker.io/lafyun/runtime-node-init:latest DEFAULT_RUNTIME_IMAGE: docker.io/lafyun/runtime-node:latest Mounts: /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-4j8zv (ro) Conditions: Type Status PodScheduled False Volumes: kube-api-access-4j8zv: Type: Projected (a volume that contains injected data from multiple sources) TokenExpirationSeconds: 3607 ConfigMapName: kube-root-ca.crt ConfigMapOptional: DownwardAPI: true QoS Class: Burstable Node-Selectors: Tolerations: node.kubernetes.io/not-ready:NoExecute op=Exists for 300s node.kubernetes.io/unreachable:NoExecute op=Exists for 300s Events: Type Reason Age From Message
> 
> Warning FailedScheduling 53s default-scheduler 0/1 nodes are available: 1 Insufficient cpu. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.. Warning FailedScheduling 49s default-scheduler 0/1 nodes are available: 1 Insufficient cpu. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod..

Insufficient cpu.
